services:
  master:
    build: ./master
    ports:
      - "8000:8000"
    networks:
      - hadoop_network

  worker:
    build: ./worker
    deploy:
      replicas: 5
    environment:
      - MASTER_URL=http://master:8000
      - BLOCK_SIZE_MB=10
    volumes:
      - ./data/workers:/app/storage 
    networks:
      - hadoop_network
    depends_on:
      - master

  ingestion:
    build: ./ingestion
    ports:
      - "8002:8002"
    environment:
      - MASTER_URL=http://master:8000
      - BLOCK_SIZE_MB=10
      - REPLICATION_FACTOR=3
    networks:
      - hadoop_network
    depends_on:
      - master

  station:
    build: ./station
    deploy:
      replicas: 250
    environment:
      - INGESTION_URL=http://ingestion:8002
      - FRECUENCY_MS=500
    networks:
      - hadoop_network
    depends_on:
      - ingestion

networks:
  hadoop_network:
    driver: bridge